version: "3.9"
services: 
  web: 
    build: .
    container_name: vite-react
    command: npm run dev
    image: vite-react:latest
    ports: 
      - '3000:3000'
    volumes:
      - .:/home/web
    networks:
      - network_test
networks:
  network_test:
    external: true